// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVLiJ0ysUQ05qpCQ8annHVDsf2w6QerP4',
    appId: '1:49681467263:web:e5c366a3942ae13fd0fc4a',
    messagingSenderId: '49681467263',
    projectId: 'group932-a',
    authDomain: 'group932-a.firebaseapp.com',
    storageBucket: 'group932-a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8usX4IVz69Ep2XDLqEXzX5J19qRW-viQ',
    appId: '1:49681467263:android:7f3c861ae76b566fd0fc4a',
    messagingSenderId: '49681467263',
    projectId: 'group932-a',
    storageBucket: 'group932-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpazIRzVgjt2xM5caE5CNfhM4Pi32e6cA',
    appId: '1:49681467263:ios:da4b5b41af396d15d0fc4a',
    messagingSenderId: '49681467263',
    projectId: 'group932-a',
    storageBucket: 'group932-a.appspot.com',
    iosClientId: '49681467263-6te338as2nh60qolihnnglmm0m180c23.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezText',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpazIRzVgjt2xM5caE5CNfhM4Pi32e6cA',
    appId: '1:49681467263:ios:da4b5b41af396d15d0fc4a',
    messagingSenderId: '49681467263',
    projectId: 'group932-a',
    storageBucket: 'group932-a.appspot.com',
    iosClientId: '49681467263-6te338as2nh60qolihnnglmm0m180c23.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezText',
  );
}
