// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPlIJa233mqq95dNq2a3ZQ-5rlEB8HUYo',
    appId: '1:798657438100:web:7e39048781aebc8cb02f81',
    messagingSenderId: '798657438100',
    projectId: 'eztext-4cc00',
    authDomain: 'eztext-4cc00.firebaseapp.com',
    storageBucket: 'eztext-4cc00.appspot.com',
    measurementId: 'G-J436XEPNP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlIJa233mqq95dNq2a3ZQ-5rlEB8HUYo',
    appId: '1:798657438100:android:6d958f567f0e0f25b02f81',
    messagingSenderId: '798657438100',
    projectId: 'eztext-4cc00',
    storageBucket: 'eztext-4cc00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk2qqOqwzPjp9AOIo6o5nUUDqZhp1gDgw',
    appId: '1:798657438100:ios:3067e6fddf137d25b02f81',
    messagingSenderId: '798657438100',
    projectId: 'eztext-4cc00',
    storageBucket: 'eztext-4cc00.appspot.com',
    iosClientId: '798657438100-umfvp9ff6dmogq4rbpj62nlh9t1h6cch.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezText',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk2qqOqwzPjp9AOIo6o5nUUDqZhp1gDgw',
    appId: '1:798657438100:ios:3067e6fddf137d25b02f81',
    messagingSenderId: '798657438100',
    projectId: 'eztext-4cc00',
    storageBucket: 'eztext-4cc00.appspot.com',
    iosClientId: '798657438100-umfvp9ff6dmogq4rbpj62nlh9t1h6cch.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezText',
  );
}
